export const INIT_CART = 'INIT_CART'
export const INIT_CART_SAGA = 'INIT_CART_SAGA'


export const CHANGE_AMOUNT_CART_ITEM = 'CHANGE_AMOUNT_CART_ITEM'
export const CHANGE_AMOUNT_CART_ITEM_SAGA = 'CHANGE_AMOUNT_CART_ITEM_SAGA'

export const DELETE_CART_ITEM_SAGA = 'DELETE_CART_ITEM_SAGA'

export const DESTROY_CART = 'DESTROY_CART'
