export const INIT_SOCKET_CLIENT = 'INIT_SOCKET_CLIENT'

export const CHANGE_USER_CHAT_HEADER_INFO = 'CHANGE_USER_HEADER_INFO'

export const CHANGE_USER_CHAT_HEADER_INFO_SAGA = 'CHANGE_USER_CHAT_HEADER_INFO_SAGA'

export const CHANGE_SHOP_CHAT_HEADER_INFO = 'CHANGE_SHOP_CHAT_HEADER_INFO'

export const CHANGE_SHOP_CHAT_HEADER_INFO_SAGA = 'CHANGE_SHOP_CHAT_HEADER_INFO_SAGA'


export const CHAT_WITH_SHOP = 'CHAT_WITH_SHOP'

export const CHAT_WITH_USER = 'CHAT_WITH_USER'


export const INIT_CONVERSATION_WITH_SHOP = 'INIT_CONVERSATION_WITH_SHOP'


export const CHAT_WITH_SHOP_SUCCESS = 'CHAT_WITH_SHOP_SUCCESS'

export const CHAT_WITH_USER_SUCCESS = 'CHAT_WITH_USER_SUCCESS'

export const INIT_USER_CONVERSATION_LIST = 'INIT_USER_CONVERSATION_LIST'

export const INIT_SHOP_CONVERSATION_LIST = 'INIT_SHOP_CONVERSATION_LIST'

export const INIT_USER_MESSAGE_LIST = 'INIT_USER_MESSAGE_LIST'

export const INIT_SHOP_MESSAGE_LIST = 'INIT_SHOP_MESSAGE_LIST'
