export const INIT_SOCKET_CLIENT = 'INIT_SOCKET_CLIENT'

export const CHANGE_USER_CHAT_HEADER_INFO = 'CHANGE_USER_HEADER_INFO'

export const CHANGE_SHOP_CHAT_HEADER_INFO = 'CHANGE_SHOP_CHAT_HEADER_INFO'


export const CHAT_WITH_SHOP = 'CHAT_WITH_SHOP'

export const CHAT_WITH_USER = 'CHAT_WITH_USER'


export const CHAT_WITH_SHOP_SUCCESS = 'CHAT_WITH_SHOP_SUCCESS'

export const CHAT_WITH_USER_SUCCESS = 'CHAT_WITH_USER_SUCCESS'
