export const INIT_CHECKOUT = 'INIT_CHECKOUT'

export const RESET_CHECKOUT = 'RESET_CHECKOUT'

export const CLEAR_CART_ITEMS = 'CLEAR_CART_ITEMS'


export const CHOOSE_ALL_CART_ITEMS = 'CHOOSE_ALL_CART_ITEMS'


export const TOGGLE_CART_ITEM = 'TOGGLE_CART_ITEM'
