export const companiesConstant = {
  COUNTRIES: "COUNTRIES",
  GET_COMPANIES: "GET_COMPANIES",
  CLEAR_FILTER_COMPANIES: "CLEAR_FILTER_COMPANIES",
  GET_COMPANY: "GET_COMPANY",
  DELETE_COMPANY: "DELETE_COMPANY",
  CLEAR_DETAIL_COMPANY: "CLEAR_DETAIL_COMPANY",
  CREATE_COMPANY: "CREATE_COMPANY",
  EDIT_COMPANY: "EDIT_COMPANY",
};
