export const userManagementConstants = {
  GET_USERS: 'GET_USERS',
  SEARCH_COMPANY: "SEARCH_COMPANY",
  GET_MEMBER_DETAIL: 'GET_MEMBER_DETAIL',
  CLEAR_MEMBER_DATA: 'CLEAR_MEMBER_DATA',
  DELETE_MEMBER: 'DELETE_MEMBER',
  CREATE_MEMBER: 'CREATE_MEMBER',
  UPDATE_MEMBER: 'UPDATE_MEMBER',
};
